import json

input = '''
[
    {
      "name":"Maariyah",
      "count":99
    },
    {
      "name":"Ijay",
      "count":95
    },
    {
      "name":"Charlie",
      "count":92
    },
    {
      "name":"Bismah",
      "count":89
    },
    {
      "name":"Gian",
      "count":88
    },
    {
      "name":"Kaidinn",
      "count":84
    },
    {
      "name":"Meghan",
      "count":83
    },
    {
      "name":"Sukhmani",
      "count":81
    },
    {
      "name":"Sylvia",
      "count":80
    },
    {
      "name":"Mea",
      "count":75
    },
    {
      "name":"Ezra",
      "count":75
    },
    {
      "name":"Melice",
      "count":75
    },
    {
      "name":"Nikodem",
      "count":68
    },
    {
      "name":"Arihant",
      "count":67
    },
    {
      "name":"Faryn",
      "count":64
    },
    {
      "name":"Alishah",
      "count":63
    },
    {
      "name":"Bartosz",
      "count":59
    },
    {
      "name":"Mara",
      "count":55
    },
    {
      "name":"Deshawn",
      "count":54
    },
    {
      "name":"Atapattu",
      "count":53
    },
    {
      "name":"Corrina",
      "count":52
    },
    {
      "name":"Sharilee",
      "count":52
    },
    {
      "name":"Nikos",
      "count":45
    },
    {
      "name":"Braegan",
      "count":44
    },
    {
      "name":"Aristomenis",
      "count":44
    },
    {
      "name":"Abdulkadir",
      "count":43
    },
    {
      "name":"Fedora",
      "count":41
    },
    {
      "name":"Owain",
      "count":39
    },
    {
      "name":"Nash",
      "count":35
    },
    {
      "name":"Kalvin",
      "count":34
    },
    {
      "name":"Humza",
      "count":33
    },
    {
      "name":"Neil",
      "count":30
    },
    {
      "name":"Kloe",
      "count":29
    },
    {
      "name":"Lena",
      "count":28
    },
    {
      "name":"Jamie",
      "count":25
    },
    {
      "name":"Amina",
      "count":24
    },
    {
      "name":"Sebastian",
      "count":24
    },
    {
      "name":"Yasemin",
      "count":24
    },
    {
      "name":"Jeronimo",
      "count":23
    },
    {
      "name":"Shakira",
      "count":22
    },
    {
      "name":"Bryoni",
      "count":21
    },
    {
      "name":"Tracy",
      "count":20
    },
    {
      "name":"Alexx",
      "count":19
    },
    {
      "name":"Ahdia",
      "count":16
    },
    {
      "name":"Savanah",
      "count":15
    },
    {
      "name":"Niteesha",
      "count":11
    },
    {
      "name":"Aadit",
      "count":11
    },
    {
      "name":"Kjae",
      "count":11
    },
    {
      "name":"Taliya",
      "count":6
    },
    {
      "name":"Annabel",
      "count":2
    }
  ]
'''

info = json.loads(input)
print 'User count:', len(info)
count = 0;

for item in info:
    print 'Name', item['name']
    count=count+item['count']
print count

